name: size_hub
description: A new Flutter project.

publish_to:
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  flare_flutter: ^2.0.6
  scoped_model: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/animations/StartAnimation.flr
  fonts:
    - family: SnowburstOne
      fonts:
        - asset: assets/fonts/SnowburstOne-Regular.ttf